name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Docker Compose
      run: |
        docker-compose up -d db
        sleep 7 #make sure db is up and running first
        docker-compose up -d ghost
        docker-compose ps 

        #make sure ghost and db are running
        docker-compose ps | grep ghost 
        docker-compose ps | grep db 
        docker-compose down
	
