name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: ghost
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
  
    - name: Build and test with Docker Compose
      env:
        MYSQL_PASSWORD: ${{ vars.GHOST_DBPW }}
        MYSQL_ROOT_PASSWORD: ${{ vars.GHOST_DBPW }}
        MYSQL_DBUSER: ${{ vars.GHOST_DBUSER }}
        GHOST_DBUSER: ${{ vars.GHOST_DBUSER }}      
      run: |
        env | grep -i ghost
        docker-compose up -d db
        sleep 30 #make sure db is up and running first
        docker-compose up -d ghost
        docker-compose ps
        sudo docker-compose ps | grep ghost | grep -i up
        sudo docker-compose ps | grep db | grep -i up
        docker-compose down

